### ISSUE TITLE
Data augmentation

### ISSUE THREAD

**Issue by darsnack** [FluxML/ML-Coordination-Tracker#11]
I am starting this issue to to track the design of our data augmentation pipeline.

Here are some related existing repositories that have come up during the bi-weekly meeting:
- https://github.com/lorenzoh/DataAugmentation.jl
- https://github.com/JuliaFolds/Transducers.jl

cc @lorenzoh

**Comment by lorenzoh** [comment]
I'll soon write up some documentation for DataAugmentation.jl and update this issue.

**Comment by darsnack** [comment]
@lorenzoh this issue could use a quick update when you get the time. Feel free to close if you think DataAugmentation.jl is mature enough.

**Comment by darsnack** [comment]
I'm closing this now that DataAugmentation.jl is registered. More issues (e.g. augmentation for non-visual data) should be opened separately and specifically. Or you can open an issue on DataAugmentation.jl directly.
