### ISSUE TITLE
Add vision models

### ISSUE THREAD

**Issue by darsnack** [FluxML/ML-Coordination-Tracker#2]
Create standard models for vision tasks.

Reference issue: darsnack/FluxModels.jl#1

**Comment by darsnack** [comment]
Current progress:
- https://github.com/darsnack/Metalhead.jl/tree/darsnack/vision-refactor
- https://github.com/FluxML/Metalhead.jl/pull/70

Accepting help to finish this up.

**Comment by cyborg1995** [comment]
Hello

I would love to work on the squeezenet model.
I'm new to julia and to github but I'm familiar with dl using PyTorch. Could someone guide me on how to start working on this?
Also, which repository to fork?
Just to mention that I've joined the zulipchat.

Thanks

**Comment by darsnack** [comment]
Hi @cyborg1995. The best way to help with this issue is to push https://github.com/FluxML/Metalhead.jl/pull/70 across the finish line. Most of the models are complete, but we need to train them and add the BSON weights. I will post more tomorrow on how to add the weights to the repo, but for now, it would be a big help if you can clone the fork and attempt to train each model to full accuracy. I think this would be a great way to help out and get familiar with Flux+Julia.

**Comment by darsnack** [comment]
Closing this since Metalhead has been refactored to address this concern.
