### ISSUE TITLE
Converting ONNX models to Flux Chains

### ISSUE THREAD

**Issue by cyborg1995** [FluxML/ML-Coordination-Tracker#21]
Flux chains are easy to work with and most of the models used as starting points for ML tasks can be represented as Flux chains. So, a feature that would take the corresponding ONNX model and convert it directly to Flux chains would be useful.

This would especially be helpful for vision tasks for doing a quick test run of an architecture. Moreover, providing such a feature as part of Metalhead.jl can also be considered.

Such a feature (ONNX2Flux) would be limited in what models it can support (due to Flux chains) but can provide a good starting/testing point for pre-existing ONNX models with ease of use.

If interest exists in creating such a feature (ONNX2Flux.jl), I would be happy to work on it.

Since [ONNXmutable.jl](https://github.com/DrChainsaw/ONNXmutable.jl) already does a good job at converting ONNX to CompGraph, adding support for conversion directly to Flux chains would use that.

Suggestions are welcome.
References:
This discussion thread https://github.com/FluxML/ML-Coordination-Tracker/issues/10
https://github.com/DrChainsaw/ONNXmutable.jl

**Comment by ToucheSir** [comment]
As you note, this approach was already discussed in #10. Is there anything to add here that you think wouldn't be relevant to that thread?

**Comment by cyborg1995** [comment]
The discussion there is in more general related to ONNX to Flux for all models. Here, I plan to consider only models that can be easily represented by Flux chains.

This issue can be considered as a sub-topic to that discussion. (Although, in the future, this can be further expanded to include all relevant points/features mentioned in that issue.)

But for now, my main focus here is on providing a tool for quick prototyping using already available ONNX models.

**Comment by ToucheSir** [comment]
I believe the approach we're trying now is to directly track work via PRs on Flux (and related repos) and to move non-tracking discussion (e.g. around design) to [discussions](https://github.com/FluxML/ML-Coordination-Tracker/discussions). If you already have an idea of what you're planning to write about/track on this issue thread, I can help you migrate those to one or both of the places above. Then this issue can be closed so that we don't have two duplicates about ONNX support.

**Comment by cyborg1995** [comment]
Let's move to discussions then ;)
