### ISSUE TITLE
ComputerVision DooDads

### ISSUE THREAD

**Issue by caseykneale** [FluxML/ML-Coordination-Tracker#32]
So I was talking to Brian Chen in Discord about sorta the state of Flux. One of the things I did not mention in that conversation, was the lack of metrics for evaluating CV models, but also convenience functions for simple things like, chipping large images, and stuff like that. 

I kicked off some packages, years(?) ago when I was rightfully more optimistic about my free time. Feel free to use them as a base for other stuff, pop them into an organization, or ignore them... 

https://github.com/caseykneale/ObjectDetectionStats.jl (not complete but has some basic stuff)

https://github.com/caseykneale/ImageChipper.jl (super simple, could be extended and improved I wrote it in like a few hours)

**Comment by lorenzoh** [comment]
Cheers 👍  will make use of this once we get to detection tasks.

**Comment by darsnack** [comment]
Thanks for the links. I am closing this only cause we are cleaning up this repo.
