### ISSUE TITLE
Add RL models

### ISSUE THREAD

**Issue by darsnack** [FluxML/ML-Coordination-Tracker#4]
Add standard RL models.

**Comment by ToucheSir** [comment]
Looks like there's some standardization happening in the ecosystem as well: https://discourse.julialang.org/t/common-rl-environment-interface/41460

**Comment by darsnack** [comment]
I am thinking of closing this issue. It doesn't really make sense for RL models to be part of FluxModels.jl. It is rare that you would need an RL model and not an RL environment. So it makes more sense for all things RL to be provided by an RL-specific package.

**Comment by darsnack** [comment]
I am closing this since we are not focused on RL (for now).
