### ISSUE TITLE
Flux docs

### ISSUE THREAD

**Issue by ToucheSir** [FluxML/ML-Coordination-Tracker#8]
Tracking issues around improving documentation on Flux and related packages:

- [ ] TODO - more accessible documentation around handling params (e.g. `Params` vs `params` vs `Functor`)
- [ ] https://github.com/FluxML/fluxml.github.io/issues/64
- [ ] https://github.com/FluxML/fluxml.github.io/issues/60

**Comment by ToucheSir** [comment]
Should we link this to https://github.com/FluxML/fluxml.github.io/pull/69?

**Comment by darsnack** [comment]
Could we break this down further into more goal/action-oriented issues? Otherwise, I will close it for now.

**Comment by ToucheSir** [comment]
That sounds fine to me, this is a hold-over from before the FluxML move. We should look into if it's possible to reference https://github.com/FluxML/Flux.jl/issues/891 and more from the tracker directly.
